#ifndef EREBOR_INTERCEPTOR_ABI_H
#define EREBOR_INTERCEPTOR_ABI_H

#ifdef __BPF__
typedef __u8 uint8_t;
typedef __u16 uint16_t;
typedef __u32 uint32_t;
typedef __u64 uint64_t;
typedef __s16 int16_t;
typedef __s32 int32_t;
#else
#include <stdint.h>
#endif


/* Generated by cbindgen from erebor-interceptor-abi. Do not edit. */

#define MAX_NESTED_EFFECT_ATTEMPTS_V1 4

#define MAX_IO_URING_ENTRIES_V1 4096

#define MAX_POLICY_ACTIVATION_PROBE_KEY_BYTES_V1 72

#define MAX_ANCESTOR_PROCESS_LINEAGES_V1 8

#define MAX_EXEC_CANDIDATES_V1 8

#define MAX_ADMINISTRATIVE_ARGUMENTS_V1 256

#define MAX_ADMINISTRATIVE_ARGUMENT_BYTES_V1 4096

#define TASK_REFERENCE_ENTRY_V1 (1 << 0)

#define TASK_REFERENCE_PROCESS_V1 (1 << 1)

#define TASK_REFERENCE_PROFILE_GENERATION_V1 (1 << 2)

#define TASK_REFERENCE_ALL_V1 ((TASK_REFERENCE_ENTRY_V1 | TASK_REFERENCE_PROCESS_V1) | TASK_REFERENCE_PROFILE_GENERATION_V1)

#define TASK_ALLOC_HOOK_LSM_V1 1

#define CONSERVATIVE_PROCESS_STATE_VECTOR_V1 1

#define MAX_NETWORK_PORT_RANGES_V1 8

#define MAX_CANONICAL_PATH_COMPONENTS_V1 255

#define MAX_CANONICAL_MOUNT_SCAN_DEPTH_V1 255

#define MAX_CANONICAL_COMPONENT_BYTES_V1 255

#define CANONICAL_COMPONENT_STORAGE_BYTES_V1 256

enum binding_lifecycle_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  binding_lifecycle_state_v1_unknown = 0,
  binding_lifecycle_state_v1_preparing = 1,
  binding_lifecycle_state_v1_active = 2,
  binding_lifecycle_state_v1_draining = 3,
  binding_lifecycle_state_v1_terminating = 4,
  binding_lifecycle_state_v1_tombstoned = 5,
};
#if __STDC_VERSION__ >= 202311L
typedef enum binding_lifecycle_state_v1 binding_lifecycle_state_v1;
#else
typedef uint8_t binding_lifecycle_state_v1;
#endif // __STDC_VERSION__ >= 202311L

enum approved_exec_slot_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint64_t
#endif // __STDC_VERSION__ >= 202311L
 {
  approved_exec_slot_state_v1_unknown = 0,
  approved_exec_slot_state_v1_armed = 1,
  approved_exec_slot_state_v1_consumed = 2,
  approved_exec_slot_state_v1_expired = 3,
  approved_exec_slot_state_v1_cancelled = 4,
  approved_exec_slot_state_v1_corrupt = 5,
};
#if __STDC_VERSION__ >= 202311L
typedef enum approved_exec_slot_state_v1 approved_exec_slot_state_v1;
#else
typedef uint64_t approved_exec_slot_state_v1;
#endif // __STDC_VERSION__ >= 202311L

enum external_root_class_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  external_root_class_v1_unknown = 0,
  external_root_class_v1_initial_container_root = 1,
  external_root_class_v1_external_runtime_root = 2,
  external_root_class_v1_restored_or_unknown_root = 3,
  external_root_class_v1_unresolved_protected = 4,
};
#if __STDC_VERSION__ >= 202311L
typedef enum external_root_class_v1 external_root_class_v1;
#else
typedef uint8_t external_root_class_v1;
#endif // __STDC_VERSION__ >= 202311L

enum authority_domain_state_kind_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  authority_domain_state_kind_v1_unknown = 0,
  authority_domain_state_kind_v1_preparing = 1,
  authority_domain_state_kind_v1_active = 2,
  authority_domain_state_kind_v1_reclaimable = 3,
  authority_domain_state_kind_v1_fail_closed_overflow = 4,
  authority_domain_state_kind_v1_corrupt = 5,
};
#if __STDC_VERSION__ >= 202311L
typedef enum authority_domain_state_kind_v1 authority_domain_state_kind_v1;
#else
typedef uint8_t authority_domain_state_kind_v1;
#endif // __STDC_VERSION__ >= 202311L

enum entry_admission_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  entry_admission_state_v1_unknown = 0,
  entry_admission_state_v1_pending = 1,
  entry_admission_state_v1_claiming = 2,
  entry_admission_state_v1_committed = 3,
  entry_admission_state_v1_terminal = 4,
};
#if __STDC_VERSION__ >= 202311L
typedef enum entry_admission_state_v1 entry_admission_state_v1;
#else
typedef uint8_t entry_admission_state_v1;
#endif // __STDC_VERSION__ >= 202311L

enum entry_kind_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  entry_kind_v1_unknown = 0,
  entry_kind_v1_container_start = 1,
  entry_kind_v1_qualified_exec_probe = 2,
  entry_kind_v1_qualified_lifecycle_poststart = 3,
  entry_kind_v1_qualified_lifecycle_prestop = 4,
  entry_kind_v1_approved_administrative_exec_next_match = 5,
  entry_kind_v1_ephemeral_container = 6,
  entry_kind_v1_qualified_ci_container_action = 7,
  entry_kind_v1_checkpoint_restore_unknown = 8,
  entry_kind_v1_unknown_external = 9,
};
#if __STDC_VERSION__ >= 202311L
typedef enum entry_kind_v1 entry_kind_v1;
#else
typedef uint8_t entry_kind_v1;
#endif // __STDC_VERSION__ >= 202311L

enum entry_lifetime_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  entry_lifetime_state_v1_inactive = 0,
  entry_lifetime_state_v1_active = 1,
  entry_lifetime_state_v1_draining = 2,
  entry_lifetime_state_v1_complete = 3,
};
#if __STDC_VERSION__ >= 202311L
typedef enum entry_lifetime_state_v1 entry_lifetime_state_v1;
#else
typedef uint8_t entry_lifetime_state_v1;
#endif // __STDC_VERSION__ >= 202311L

enum entry_purpose_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  entry_purpose_v1_unknown = 0,
  entry_purpose_v1_qualified_joined_purpose = 1,
  entry_purpose_v1_approved_administrative_next_match = 2,
};
#if __STDC_VERSION__ >= 202311L
typedef enum entry_purpose_v1 entry_purpose_v1;
#else
typedef uint8_t entry_purpose_v1;
#endif // __STDC_VERSION__ >= 202311L

enum image_provenance_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  image_provenance_state_v1_unknown = 0,
  image_provenance_state_v1_preparing = 1,
  image_provenance_state_v1_active = 2,
  image_provenance_state_v1_complete = 3,
  image_provenance_state_v1_outcome_unknown = 4,
};
#if __STDC_VERSION__ >= 202311L
typedef enum image_provenance_state_v1 image_provenance_state_v1;
#else
typedef uint8_t image_provenance_state_v1;
#endif // __STDC_VERSION__ >= 202311L

enum exec_guard_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  exec_guard_state_v1_none = 0,
  exec_guard_state_v1_preparing = 1,
  exec_guard_state_v1_commit_pending = 2,
  exec_guard_state_v1_outcome_unknown = 3,
};
#if __STDC_VERSION__ >= 202311L
typedef enum exec_guard_state_v1 exec_guard_state_v1;
#else
typedef uint8_t exec_guard_state_v1;
#endif // __STDC_VERSION__ >= 202311L

enum initial_root_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint64_t
#endif // __STDC_VERSION__ >= 202311L
 {
  initial_root_state_v1_unarmed = 0,
  initial_root_state_v1_available = 1,
  initial_root_state_v1_consumed = 2,
};
#if __STDC_VERSION__ >= 202311L
typedef enum initial_root_state_v1 initial_root_state_v1;
#else
typedef uint64_t initial_root_state_v1;
#endif // __STDC_VERSION__ >= 202311L

enum runtime_bootstrap_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint64_t
#endif // __STDC_VERSION__ >= 202311L
 {
  runtime_bootstrap_state_v1_unarmed = 0,
  runtime_bootstrap_state_v1_armed = 1,
  runtime_bootstrap_state_v1_handoff_pending = 2,
  runtime_bootstrap_state_v1_consumed = 3,
  runtime_bootstrap_state_v1_expired = 4,
  runtime_bootstrap_state_v1_corrupt = 5,
};
#if __STDC_VERSION__ >= 202311L
typedef enum runtime_bootstrap_state_v1 runtime_bootstrap_state_v1;
#else
typedef uint64_t runtime_bootstrap_state_v1;
#endif // __STDC_VERSION__ >= 202311L

enum installed_role_class_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  installed_role_class_v1_unknown = 0,
  installed_role_class_v1_initial_role = 1,
  installed_role_class_v1_runtime_external_restricted = 2,
  installed_role_class_v1_fail_closed_unknown = 3,
  installed_role_class_v1_qualified_registered_role = 4,
  installed_role_class_v1_approved_administrative_role = 5,
};
#if __STDC_VERSION__ >= 202311L
typedef enum installed_role_class_v1 installed_role_class_v1;
#else
typedef uint8_t installed_role_class_v1;
#endif // __STDC_VERSION__ >= 202311L

enum exact_device_type_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  exact_device_type_v1_unknown = 0,
  exact_device_type_v1_character = 1,
  exact_device_type_v1_block = 2,
};
#if __STDC_VERSION__ >= 202311L
typedef enum exact_device_type_v1 exact_device_type_v1;
#else
typedef uint8_t exact_device_type_v1;
#endif // __STDC_VERSION__ >= 202311L

enum effect_observation_reason_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  effect_observation_reason_v1_unknown = 0,
  effect_observation_reason_v1_exact_policy_allow = 1,
  effect_observation_reason_v1_exact_policy_audit_allow = 2,
  effect_observation_reason_v1_would_deny = 3,
  effect_observation_reason_v1_prior_lsm_denial = 4,
  effect_observation_reason_v1_missing_identity = 5,
  effect_observation_reason_v1_corrupt_identity_or_generation = 6,
  effect_observation_reason_v1_unresolved_object = 7,
  effect_observation_reason_v1_unsupported_object = 8,
  effect_observation_reason_v1_exact_policy_deny = 9,
  effect_observation_reason_v1_exception_unavailable = 10,
  effect_observation_reason_v1_path_tree_policy_deny = 11,
  effect_observation_reason_v1_network_response_fence = 12,
  effect_observation_reason_v1_runtime_bootstrap_authority = 13,
};
#if __STDC_VERSION__ >= 202311L
typedef enum effect_observation_reason_v1 effect_observation_reason_v1;
#else
typedef uint8_t effect_observation_reason_v1;
#endif // __STDC_VERSION__ >= 202311L

enum effect_physical_result_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  effect_physical_result_v1_unknown_after_pre_effect = 0,
  effect_physical_result_v1_denied_before_effect = 1,
  effect_physical_result_v1_packet_dropped_after_rewrite = 2,
};
#if __STDC_VERSION__ >= 202311L
typedef enum effect_physical_result_v1 effect_physical_result_v1;
#else
typedef uint8_t effect_physical_result_v1;
#endif // __STDC_VERSION__ >= 202311L

enum exact_object_binding_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  exact_object_binding_state_v1_unknown = 0,
  exact_object_binding_state_v1_read_back = 1,
  exact_object_binding_state_v1_active_dynamic = 2,
};
#if __STDC_VERSION__ >= 202311L
typedef enum exact_object_binding_state_v1 exact_object_binding_state_v1;
#else
typedef uint8_t exact_object_binding_state_v1;
#endif // __STDC_VERSION__ >= 202311L

enum effect_attempt_hook_v1
#if __STDC_VERSION__ >= 202311L
  : uint16_t
#endif // __STDC_VERSION__ >= 202311L
 {
  effect_attempt_hook_v1_unknown = 0,
  effect_attempt_hook_v1_file_open = 1,
};
#if __STDC_VERSION__ >= 202311L
typedef enum effect_attempt_hook_v1 effect_attempt_hook_v1;
#else
typedef uint16_t effect_attempt_hook_v1;
#endif // __STDC_VERSION__ >= 202311L

enum exception_binding_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  exception_binding_state_v1_unknown = 0,
  exception_binding_state_v1_preparing = 1,
  exception_binding_state_v1_active = 2,
  exception_binding_state_v1_retiring = 3,
};
#if __STDC_VERSION__ >= 202311L
typedef enum exception_binding_state_v1 exception_binding_state_v1;
#else
typedef uint8_t exception_binding_state_v1;
#endif // __STDC_VERSION__ >= 202311L

enum exception_receipt_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  exception_receipt_state_v1_unknown = 0,
  exception_receipt_state_v1_claiming = 1,
  exception_receipt_state_v1_consumed = 2,
  exception_receipt_state_v1_denied_exhausted = 3,
  exception_receipt_state_v1_denied_expired = 4,
  exception_receipt_state_v1_denied_corrupt = 5,
  exception_receipt_state_v1_reconciliation_required = 6,
};
#if __STDC_VERSION__ >= 202311L
typedef enum exception_receipt_state_v1 exception_receipt_state_v1;
#else
typedef uint8_t exception_receipt_state_v1;
#endif // __STDC_VERSION__ >= 202311L

enum exception_runtime_state_kind_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  exception_runtime_state_kind_v1_unknown = 0,
  exception_runtime_state_kind_v1_active = 1,
  exception_runtime_state_kind_v1_exhausted = 2,
  exception_runtime_state_kind_v1_expired = 3,
  exception_runtime_state_kind_v1_reconciliation_required = 4,
};
#if __STDC_VERSION__ >= 202311L
typedef enum exception_runtime_state_kind_v1 exception_runtime_state_kind_v1;
#else
typedef uint8_t exception_runtime_state_kind_v1;
#endif // __STDC_VERSION__ >= 202311L

enum exception_use_identity_kind_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  exception_use_identity_kind_v1_unknown = 0,
  exception_use_identity_kind_v1_claim_slot = 1,
  exception_use_identity_kind_v1_kernel_effect_attempt = 2,
};
#if __STDC_VERSION__ >= 202311L
typedef enum exception_use_identity_kind_v1 exception_use_identity_kind_v1;
#else
typedef uint8_t exception_use_identity_kind_v1;
#endif // __STDC_VERSION__ >= 202311L

enum runtime_bootstrap_object_kind_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  runtime_bootstrap_object_kind_v1_unknown = 0,
  runtime_bootstrap_object_kind_v1_pipe = 1,
  runtime_bootstrap_object_kind_v1_memfd = 2,
};
#if __STDC_VERSION__ >= 202311L
typedef enum runtime_bootstrap_object_kind_v1 runtime_bootstrap_object_kind_v1;
#else
typedef uint8_t runtime_bootstrap_object_kind_v1;
#endif // __STDC_VERSION__ >= 202311L

enum io_uring_execution_state_kind_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  io_uring_execution_state_kind_v1_inactive = 0,
  io_uring_execution_state_kind_v1_active = 1,
  io_uring_execution_state_kind_v1_fail_closed = 2,
};
#if __STDC_VERSION__ >= 202311L
typedef enum io_uring_execution_state_kind_v1 io_uring_execution_state_kind_v1;
#else
typedef uint8_t io_uring_execution_state_kind_v1;
#endif // __STDC_VERSION__ >= 202311L

enum io_uring_request_state_kind_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  io_uring_request_state_kind_v1_unknown = 0,
  io_uring_request_state_kind_v1_submitted = 1,
  io_uring_request_state_kind_v1_completed = 2,
  io_uring_request_state_kind_v1_corrupt = 3,
};
#if __STDC_VERSION__ >= 202311L
typedef enum io_uring_request_state_kind_v1 io_uring_request_state_kind_v1;
#else
typedef uint8_t io_uring_request_state_kind_v1;
#endif // __STDC_VERSION__ >= 202311L

enum io_uring_restriction_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  io_uring_restriction_state_v1_unknown = 0,
  io_uring_restriction_state_v1_none = 1,
  io_uring_restriction_state_v1_exact_read_write = 2,
};
#if __STDC_VERSION__ >= 202311L
typedef enum io_uring_restriction_state_v1 io_uring_restriction_state_v1;
#else
typedef uint8_t io_uring_restriction_state_v1;
#endif // __STDC_VERSION__ >= 202311L

enum io_uring_ring_state_kind_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  io_uring_ring_state_kind_v1_unknown = 0,
  io_uring_ring_state_kind_v1_disabled = 1,
  io_uring_ring_state_kind_v1_restricted = 2,
  io_uring_ring_state_kind_v1_active = 3,
  io_uring_ring_state_kind_v1_corrupt = 4,
  io_uring_ring_state_kind_v1_closed = 5,
};
#if __STDC_VERSION__ >= 202311L
typedef enum io_uring_ring_state_kind_v1 io_uring_ring_state_kind_v1;
#else
typedef uint8_t io_uring_ring_state_kind_v1;
#endif // __STDC_VERSION__ >= 202311L

enum io_uring_setup_state_kind_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  io_uring_setup_state_kind_v1_inactive = 0,
  io_uring_setup_state_kind_v1_prepared = 1,
  io_uring_setup_state_kind_v1_authorized = 2,
  io_uring_setup_state_kind_v1_invalid = 3,
};
#if __STDC_VERSION__ >= 202311L
typedef enum io_uring_setup_state_kind_v1 io_uring_setup_state_kind_v1;
#else
typedef uint8_t io_uring_setup_state_kind_v1;
#endif // __STDC_VERSION__ >= 202311L

enum ipc_channel_kind_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  ipc_channel_kind_v1_unknown = 0,
  ipc_channel_kind_v1_unix_stream = 1,
};
#if __STDC_VERSION__ >= 202311L
typedef enum ipc_channel_kind_v1 ipc_channel_kind_v1;
#else
typedef uint8_t ipc_channel_kind_v1;
#endif // __STDC_VERSION__ >= 202311L

enum ipc_operation_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  ipc_operation_v1_unknown = 0,
  ipc_operation_v1_connect = 1,
  ipc_operation_v1_send = 2,
  ipc_operation_v1_receive = 3,
};
#if __STDC_VERSION__ >= 202311L
typedef enum ipc_operation_v1 ipc_operation_v1;
#else
typedef uint8_t ipc_operation_v1;
#endif // __STDC_VERSION__ >= 202311L

enum ipc_socket_state_kind_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  ipc_socket_state_kind_v1_unknown = 0,
  ipc_socket_state_kind_v1_endpoint = 1,
  ipc_socket_state_kind_v1_connected = 2,
};
#if __STDC_VERSION__ >= 202311L
typedef enum ipc_socket_state_kind_v1 ipc_socket_state_kind_v1;
#else
typedef uint8_t ipc_socket_state_kind_v1;
#endif // __STDC_VERSION__ >= 202311L

enum kernel_real_parent_change_reason_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  kernel_real_parent_change_reason_v1_unknown = 0,
  kernel_real_parent_change_reason_v1_birth = 1,
  kernel_real_parent_change_reason_v1_clone_parent = 2,
  kernel_real_parent_change_reason_v1_parent_exit_or_reparent = 3,
};
#if __STDC_VERSION__ >= 202311L
typedef enum kernel_real_parent_change_reason_v1 kernel_real_parent_change_reason_v1;
#else
typedef uint8_t kernel_real_parent_change_reason_v1;
#endif // __STDC_VERSION__ >= 202311L

enum kernel_effect_family_v1
#if __STDC_VERSION__ >= 202311L
  : uint16_t
#endif // __STDC_VERSION__ >= 202311L
 {
  kernel_effect_family_v1_unknown = 0,
  kernel_effect_family_v1_exec = 1,
  kernel_effect_family_v1_file = 2,
  kernel_effect_family_v1_network = 3,
  kernel_effect_family_v1_device = 4,
  kernel_effect_family_v1_privilege = 5,
  kernel_effect_family_v1_ipc = 6,
  kernel_effect_family_v1_mount = 7,
};
#if __STDC_VERSION__ >= 202311L
typedef enum kernel_effect_family_v1 kernel_effect_family_v1;
#else
typedef uint16_t kernel_effect_family_v1;
#endif // __STDC_VERSION__ >= 202311L

enum kernel_effect_operation_v1
#if __STDC_VERSION__ >= 202311L
  : uint16_t
#endif // __STDC_VERSION__ >= 202311L
 {
  kernel_effect_operation_v1_unknown = 0,
  kernel_effect_operation_v1_execute = 1,
  kernel_effect_operation_v1_open_read = 2,
  kernel_effect_operation_v1_open_write = 3,
  kernel_effect_operation_v1_read = 4,
  kernel_effect_operation_v1_write = 5,
  kernel_effect_operation_v1_ioctl = 6,
  kernel_effect_operation_v1_mmap_read = 7,
  kernel_effect_operation_v1_mmap_write = 8,
  kernel_effect_operation_v1_mmap_exec = 9,
  kernel_effect_operation_v1_mprotect = 10,
  kernel_effect_operation_v1_ipc_access = 11,
  kernel_effect_operation_v1_connect = 12,
  kernel_effect_operation_v1_send = 13,
  kernel_effect_operation_v1_ptrace = 14,
  kernel_effect_operation_v1_signal = 15,
  kernel_effect_operation_v1_unlink = 16,
  kernel_effect_operation_v1_link = 17,
  kernel_effect_operation_v1_rename = 18,
  kernel_effect_operation_v1_mount = 19,
  kernel_effect_operation_v1_unmount = 20,
  kernel_effect_operation_v1_pivot_root = 21,
  kernel_effect_operation_v1_move_mount = 22,
  kernel_effect_operation_v1_capability = 23,
  kernel_effect_operation_v1_bpf = 24,
  kernel_effect_operation_v1_create = 25,
  kernel_effect_operation_v1_setattr = 26,
  kernel_effect_operation_v1_io_uring_setup = 27,
  kernel_effect_operation_v1_io_uring_register = 28,
  kernel_effect_operation_v1_io_uring_sqpoll = 29,
  kernel_effect_operation_v1_io_uring_override_creds = 30,
  kernel_effect_operation_v1_io_uring_command = 31,
  kernel_effect_operation_v1_socket_create = 32,
  kernel_effect_operation_v1_bind = 33,
  kernel_effect_operation_v1_listen = 34,
  kernel_effect_operation_v1_accept = 35,
  kernel_effect_operation_v1_receive = 36,
  kernel_effect_operation_v1_shutdown = 37,
  kernel_effect_operation_v1_setsockopt = 38,
};
#if __STDC_VERSION__ >= 202311L
typedef enum kernel_effect_operation_v1 kernel_effect_operation_v1;
#else
typedef uint16_t kernel_effect_operation_v1;
#endif // __STDC_VERSION__ >= 202311L

enum network_address_family_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  network_address_family_v1_unknown = 0,
  network_address_family_v1_ipv4 = 1,
  network_address_family_v1_ipv6 = 2,
};
#if __STDC_VERSION__ >= 202311L
typedef enum network_address_family_v1 network_address_family_v1;
#else
typedef uint8_t network_address_family_v1;
#endif // __STDC_VERSION__ >= 202311L

enum network_protocol_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  network_protocol_v1_unknown = 0,
  network_protocol_v1_tcp = 6,
  network_protocol_v1_udp = 17,
};
#if __STDC_VERSION__ >= 202311L
typedef enum network_protocol_v1 network_protocol_v1;
#else
typedef uint8_t network_protocol_v1;
#endif // __STDC_VERSION__ >= 202311L

enum network_response_scope_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  network_response_scope_v1_unknown = 0,
  network_response_scope_v1_whole_socket = 1,
};
#if __STDC_VERSION__ >= 202311L
typedef enum network_response_scope_v1 network_response_scope_v1;
#else
typedef uint8_t network_response_scope_v1;
#endif // __STDC_VERSION__ >= 202311L

enum network_socket_state_kind_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  network_socket_state_kind_v1_unknown = 0,
  network_socket_state_kind_v1_active = 1,
  network_socket_state_kind_v1_fenced = 2,
  network_socket_state_kind_v1_tombstoned = 3,
  network_socket_state_kind_v1_reconciliation_required = 4,
};
#if __STDC_VERSION__ >= 202311L
typedef enum network_socket_state_kind_v1 network_socket_state_kind_v1;
#else
typedef uint8_t network_socket_state_kind_v1;
#endif // __STDC_VERSION__ >= 202311L

enum mount_topology_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  mount_topology_state_v1_unknown = 0,
  mount_topology_state_v1_dirty = 1,
  mount_topology_state_v1_clean = 2,
};
#if __STDC_VERSION__ >= 202311L
typedef enum mount_topology_state_v1 mount_topology_state_v1;
#else
typedef uint8_t mount_topology_state_v1;
#endif // __STDC_VERSION__ >= 202311L

enum pending_exec_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  pending_exec_state_v1_unknown = 0,
  pending_exec_state_v1_preparing = 1,
  pending_exec_state_v1_commit_pending = 2,
  pending_exec_state_v1_pre_ponr_failed = 3,
  pending_exec_state_v1_post_ponr_fatal = 4,
  pending_exec_state_v1_success = 5,
  pending_exec_state_v1_outcome_unknown = 6,
};
#if __STDC_VERSION__ >= 202311L
typedef enum pending_exec_state_v1 pending_exec_state_v1;
#else
typedef uint8_t pending_exec_state_v1;
#endif // __STDC_VERSION__ >= 202311L

enum pending_administrative_match_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  pending_administrative_match_state_v1_unknown = 0,
  pending_administrative_match_state_v1_arguments_matched = 1,
  pending_administrative_match_state_v1_slot_consumed = 2,
};
#if __STDC_VERSION__ >= 202311L
typedef enum pending_administrative_match_state_v1 pending_administrative_match_state_v1;
#else
typedef uint8_t pending_administrative_match_state_v1;
#endif // __STDC_VERSION__ >= 202311L

enum physical_decision_kind_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  physical_decision_kind_v1_allow = 0,
  physical_decision_kind_v1_audit_allow = 1,
  physical_decision_kind_v1_deny = 2,
};
#if __STDC_VERSION__ >= 202311L
typedef enum physical_decision_kind_v1 physical_decision_kind_v1;
#else
typedef uint8_t physical_decision_kind_v1;
#endif // __STDC_VERSION__ >= 202311L

enum policy_activation_probe_map_kind_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  policy_activation_probe_map_kind_v1_unknown = 0,
  policy_activation_probe_map_kind_v1_effect_decision = 1,
  policy_activation_probe_map_kind_v1_effect_default = 2,
  policy_activation_probe_map_kind_v1_ipc_relationship = 3,
  policy_activation_probe_map_kind_v1_device_effect = 4,
  policy_activation_probe_map_kind_v1_process_control = 5,
  policy_activation_probe_map_kind_v1_administrative_slot_cancel = 6,
  policy_activation_probe_map_kind_v1_mount_reconciliation = 7,
  policy_activation_probe_map_kind_v1_network_destination = 8,
};
#if __STDC_VERSION__ >= 202311L
typedef enum policy_activation_probe_map_kind_v1 policy_activation_probe_map_kind_v1;
#else
typedef uint8_t policy_activation_probe_map_kind_v1;
#endif // __STDC_VERSION__ >= 202311L

enum policy_generation_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  policy_generation_state_v1_unknown = 0,
  policy_generation_state_v1_preparing = 1,
  policy_generation_state_v1_read_back = 2,
  policy_generation_state_v1_active = 3,
  policy_generation_state_v1_rejected = 4,
  policy_generation_state_v1_retiring = 5,
  policy_generation_state_v1_tombstoned = 6,
};
#if __STDC_VERSION__ >= 202311L
typedef enum policy_generation_state_v1 policy_generation_state_v1;
#else
typedef uint8_t policy_generation_state_v1;
#endif // __STDC_VERSION__ >= 202311L

enum policy_generation_mode_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  policy_generation_mode_v1_unknown = 0,
  policy_generation_mode_v1_observe = 1,
  policy_generation_mode_v1_protect = 2,
};
#if __STDC_VERSION__ >= 202311L
typedef enum policy_generation_mode_v1 policy_generation_mode_v1;
#else
typedef uint8_t policy_generation_mode_v1;
#endif // __STDC_VERSION__ >= 202311L

enum process_security_state_kind_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  process_security_state_kind_v1_unknown = 0,
  process_security_state_kind_v1_allocating = 1,
  process_security_state_kind_v1_active = 2,
  process_security_state_kind_v1_exiting = 3,
  process_security_state_kind_v1_reclaimable = 4,
  process_security_state_kind_v1_fail_closed_overflow = 5,
  process_security_state_kind_v1_corrupt = 6,
};
#if __STDC_VERSION__ >= 202311L
typedef enum process_security_state_kind_v1 process_security_state_kind_v1;
#else
typedef uint8_t process_security_state_kind_v1;
#endif // __STDC_VERSION__ >= 202311L

enum process_state_vector_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  process_state_vector_state_v1_unknown = 0,
  process_state_vector_state_v1_preparing = 1,
  process_state_vector_state_v1_active = 2,
  process_state_vector_state_v1_retiring = 3,
};
#if __STDC_VERSION__ >= 202311L
typedef enum process_state_vector_state_v1 process_state_vector_state_v1;
#else
typedef uint8_t process_state_vector_state_v1;
#endif // __STDC_VERSION__ >= 202311L

enum process_execution_started_by_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  process_execution_started_by_v1_unknown = 0,
  process_execution_started_by_v1_process_birth = 1,
  process_execution_started_by_v1_exec_commit = 2,
};
#if __STDC_VERSION__ >= 202311L
typedef enum process_execution_started_by_v1 process_execution_started_by_v1;
#else
typedef uint8_t process_execution_started_by_v1;
#endif // __STDC_VERSION__ >= 202311L

enum process_execution_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  process_execution_state_v1_unknown = 0,
  process_execution_state_v1_preparing = 1,
  process_execution_state_v1_active = 2,
  process_execution_state_v1_complete = 3,
  process_execution_state_v1_outcome_unknown = 4,
};
#if __STDC_VERSION__ >= 202311L
typedef enum process_execution_state_v1 process_execution_state_v1;
#else
typedef uint8_t process_execution_state_v1;
#endif // __STDC_VERSION__ >= 202311L

enum reference_tombstone_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  reference_tombstone_state_v1_unknown = 0,
  reference_tombstone_state_v1_preparing = 1,
  reference_tombstone_state_v1_owned = 2,
  reference_tombstone_state_v1_released = 3,
  reference_tombstone_state_v1_reclaimable = 4,
};
#if __STDC_VERSION__ >= 202311L
typedef enum reference_tombstone_state_v1 reference_tombstone_state_v1;
#else
typedef uint8_t reference_tombstone_state_v1;
#endif // __STDC_VERSION__ >= 202311L

enum task_coordinate_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  task_coordinate_state_v1_unknown = 0,
  task_coordinate_state_v1_allocating = 1,
  task_coordinate_state_v1_coordinates_finalized = 2,
  task_coordinate_state_v1_runnable = 3,
  task_coordinate_state_v1_exited = 4,
  task_coordinate_state_v1_failed = 5,
  task_coordinate_state_v1_fail_closed_unknown = 6,
};
#if __STDC_VERSION__ >= 202311L
typedef enum task_coordinate_state_v1 task_coordinate_state_v1;
#else
typedef uint8_t task_coordinate_state_v1;
#endif // __STDC_VERSION__ >= 202311L

enum task_effect_attempt_frame_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  task_effect_attempt_frame_state_v1_unknown = 0,
  task_effect_attempt_frame_state_v1_preparing = 1,
  task_effect_attempt_frame_state_v1_decided = 2,
  task_effect_attempt_frame_state_v1_returned = 3,
  task_effect_attempt_frame_state_v1_cancelled = 4,
};
#if __STDC_VERSION__ >= 202311L
typedef enum task_effect_attempt_frame_state_v1 task_effect_attempt_frame_state_v1;
#else
typedef uint8_t task_effect_attempt_frame_state_v1;
#endif // __STDC_VERSION__ >= 202311L

enum task_effect_attempt_state_kind_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  task_effect_attempt_state_kind_v1_inactive = 0,
  task_effect_attempt_state_kind_v1_active = 1,
  task_effect_attempt_state_kind_v1_overflow_fail_closed = 2,
  task_effect_attempt_state_kind_v1_task_exited = 3,
};
#if __STDC_VERSION__ >= 202311L
typedef enum task_effect_attempt_state_kind_v1 task_effect_attempt_state_kind_v1;
#else
typedef uint8_t task_effect_attempt_state_kind_v1;
#endif // __STDC_VERSION__ >= 202311L

typedef struct id128_v1 {
  uint64_t high;
  uint64_t low;
} id128_v1;
#define id128_v1_ZERO (id128_v1){ .high = 0, .low = 0 }

typedef struct canonical_mount_root_key_v1 {
  uint64_t profile_generation_ref_id;
  struct id128_v1 binding_id;
  uint64_t topology_generation;
  uint64_t root_inode;
  uint32_t mount_namespace_inode;
  uint32_t filesystem_device;
} canonical_mount_root_key_v1;

typedef struct canonical_mount_root_v1 {
  uint64_t selected_mount_id_unique;
  uint64_t snapshot_digest_id;
  uint32_t graph_prefix_state_id;
  uint32_t reserved;
} canonical_mount_root_v1;

typedef struct canonical_path_component_v1 {
  uint16_t length;
  uint8_t bytes[CANONICAL_COMPONENT_STORAGE_BYTES_V1];
} canonical_path_component_v1;

typedef struct approved_exec_argument_key_v1 {
  struct id128_v1 proof_id;
  uint16_t argument_index;
  uint16_t argument_length;
  uint8_t argument_bytes[MAX_ADMINISTRATIVE_ARGUMENT_BYTES_V1];
  uint8_t reserved[4];
} approved_exec_argument_key_v1;

typedef struct approved_exec_slot_key_v1 {
  struct id128_v1 node_boot_id;
  struct id128_v1 cgroup_binding_id;
} approved_exec_slot_key_v1;

typedef struct bounded_administrative_argv_v1 {
  uint16_t argument_count;
  uint16_t total_argument_bytes;
  uint16_t argument_lengths[MAX_ADMINISTRATIVE_ARGUMENTS_V1];
  uint8_t argument_bytes[MAX_ADMINISTRATIVE_ARGUMENT_BYTES_V1];
} bounded_administrative_argv_v1;

typedef struct exact_executable_candidate_v1 {
  uint64_t inode;
  uint32_t mount_namespace_inode;
  uint32_t mount_id;
  uint32_t filesystem_device;
  uint32_t inode_generation;
} exact_executable_candidate_v1;

typedef struct approved_exec_slot_v1 {
  struct id128_v1 proof_id;
  struct id128_v1 claim_slot_id;
  uint8_t authorization_body_sha256[32];
  struct id128_v1 cgroup_binding_nonce;
  uint64_t container_generation;
  struct bounded_administrative_argv_v1 expected_argv;
  uint8_t reserved_pre_executable[4];
  struct exact_executable_candidate_v1 resolved_executable;
  uint32_t approved_role_numeric_id;
  external_root_class_v1 expected_root_class;
  uint8_t reserved_0[3];
  uint64_t profile_generation_ref_id;
  uint32_t exception_numeric_handle;
  uint32_t reserved_after_exception;
  uint64_t deadline_boottime_ns;
  approved_exec_slot_state_v1 state;
  uint64_t transition_version;
} approved_exec_slot_v1;

typedef struct created_by_edge_v1 {
  uint64_t child_task_cookie;
  uint64_t creator_task_cookie;
  struct id128_v1 child_process_lineage_id;
  struct id128_v1 creator_process_lineage_id;
  struct id128_v1 clone_attempt_id;
  uint64_t clone_flags;
  uint32_t task_alloc_hook_id;
  uint32_t reserved;
} created_by_edge_v1;

typedef struct authority_domain_state_v1 {
  struct id128_v1 authority_domain_id;
  struct id128_v1 node_boot_id;
  uint64_t label_epoch;
  uint64_t domain_epoch;
  uint64_t live_process_refs;
  uint64_t response_plan_refs;
  uint64_t reconciliation_hold_refs;
  uint64_t potential_sensitive_bits;
  uint64_t observed_sensitive_bits;
  uint64_t effective_restriction_set_ref_id;
  uint64_t effective_response_set_ref_id;
  uint64_t retained_generation_set_ref_id;
  uint64_t transition_version;
  uint64_t transition_guard;
  authority_domain_state_kind_v1 state;
  uint8_t reserved[7];
} authority_domain_state_v1;

typedef struct entry_security_state_v1 {
  struct id128_v1 entry_instance_id;
  struct id128_v1 node_boot_id;
  uint64_t label_epoch;
  struct id128_v1 execution_set_id;
  struct id128_v1 claim_slot_id;
  uint64_t root_task_cookie;
  struct id128_v1 root_process_state_id;
  struct id128_v1 committed_execution_id;
  uint64_t live_task_refs;
  uint64_t transition_version;
  entry_kind_v1 entry_kind;
  entry_admission_state_v1 admission_state;
  entry_lifetime_state_v1 lifetime_state;
  uint8_t terminal_reason;
  uint8_t reserved_state[4];
  uint64_t transition_guard;
} entry_security_state_v1;

typedef struct image_provenance_v1 {
  struct id128_v1 image_provenance_id;
  uint16_t candidate_count;
  uint8_t reserved_0[6];
  struct exact_executable_candidate_v1 ordered_candidates[MAX_EXEC_CANDIDATES_V1];
  uint64_t transition_version;
  image_provenance_state_v1 state;
  uint8_t reserved_1[7];
} image_provenance_v1;

typedef struct binding_activation_target_key_v1 {
  struct id128_v1 binding_id;
  uint64_t profile_generation_ref_id;
} binding_activation_target_key_v1;

typedef struct execution_set_binding_state_v1 {
  struct id128_v1 binding_id;
  struct id128_v1 binding_nonce;
  struct id128_v1 node_boot_id;
  struct id128_v1 execution_set_id;
  struct id128_v1 protected_scope_id;
  struct id128_v1 profile_id;
  uint64_t label_epoch;
  uint64_t active_profile_generation_ref_id;
  uint64_t root_cgroup_id;
  struct id128_v1 root_cgroup_live_interval_id;
  uint64_t container_generation;
  uint64_t lifecycle_generation;
  uint64_t transition_version;
  uint32_t initial_role_id;
  uint32_t external_role_id;
  binding_lifecycle_state_v1 lifecycle_state;
  uint8_t reserved[7];
  initial_root_state_v1 initial_root_state;
  runtime_bootstrap_state_v1 runtime_bootstrap_state;
  uint64_t runtime_bootstrap_deadline_boottime_ns;
  struct id128_v1 runtime_bootstrap_entry_instance_id;
  uint64_t runtime_bootstrap_handoff_task_cookie;
} execution_set_binding_state_v1;

typedef struct external_root_classification_v1 {
  struct id128_v1 node_boot_id;
  uint64_t label_epoch;
  uint64_t task_cookie;
  struct id128_v1 process_state_id;
  struct id128_v1 entry_instance_id;
  struct id128_v1 execution_set_id;
  struct id128_v1 cgroup_binding_id;
  struct id128_v1 cgroup_lifetime_id;
  uint64_t creator_task_cookie;
  struct id128_v1 administrative_approval_proof_id;
  struct id128_v1 administrative_claim_slot_id;
  uint64_t profile_generation_ref_id;
  uint32_t installed_role_numeric_id;
  external_root_class_v1 root_class;
  entry_purpose_v1 purpose;
  installed_role_class_v1 installed_role_class;
  uint8_t reserved;
  uint64_t classified_boottime_ns;
} external_root_classification_v1;

typedef struct effect_decision_key_v1 {
  uint64_t profile_generation_ref_id;
  uint32_t active_role_id;
  uint16_t entry_kind;
  uint16_t effect_family;
  uint16_t operation;
  uint16_t reserved;
  uint8_t reserved_alignment[4];
  uint64_t composite_atom_id;
  uint64_t exact_object_key_id;
  uint32_t process_state_vector_id;
  binding_lifecycle_state_v1 binding_lifecycle_state;
  uint8_t reserved_tail[3];
} effect_decision_key_v1;

typedef struct effect_default_key_v1 {
  uint64_t profile_generation_ref_id;
  uint32_t active_role_id;
  uint16_t entry_kind;
  uint16_t effect_family;
  uint16_t operation;
  uint16_t reserved;
  uint8_t reserved_alignment[4];
  uint64_t composite_atom_id;
  uint32_t process_state_vector_id;
  binding_lifecycle_state_v1 binding_lifecycle_state;
  uint8_t reserved_tail[3];
} effect_default_key_v1;

typedef struct device_effect_key_v1 {
  uint64_t profile_generation_ref_id;
  uint64_t mount_id_unique;
  uint64_t inode;
  uint64_t exact_object_key_id;
  uint32_t active_role_id;
  uint32_t process_state_vector_id;
  uint32_t mount_namespace_inode;
  uint32_t filesystem_device;
  uint32_t inode_generation;
  uint32_t device_major;
  uint32_t device_minor;
  uint32_t ioctl_command;
  uint16_t entry_kind;
  uint16_t operation;
  binding_lifecycle_state_v1 binding_lifecycle_state;
  exact_device_type_v1 device_type;
  uint8_t command_wildcard;
  uint8_t reserved;
} device_effect_key_v1;

typedef struct effect_observation_health_v1 {
  uint64_t attempted;
  uint64_t suppressed;
  uint64_t requested;
  uint64_t emitted;
  uint64_t lost;
  uint64_t classifier_miss_count;
  uint64_t unresolved;
  uint64_t next_sequence;
} effect_observation_health_v1;

typedef struct exact_file_object_key_v1 {
  uint64_t profile_generation_ref_id;
  uint64_t mount_id_unique;
  uint64_t inode;
  uint32_t mount_namespace_inode;
  uint32_t filesystem_device;
  uint32_t inode_generation;
  uint32_t reserved;
} exact_file_object_key_v1;

typedef struct network_namespace_generation_v1 {
  uint64_t network_namespace_address;
  uint32_t network_namespace_inode;
  uint32_t reserved;
} network_namespace_generation_v1;

typedef struct effect_observation_v1 {
  uint64_t observed_boottime_ns;
  uint64_t source_sequence;
  uint32_t source_cpu_id;
  uint8_t reserved_source[4];
  uint64_t task_cookie;
  uint64_t profile_generation_ref_id;
  struct id128_v1 process_lineage_id;
  struct id128_v1 process_instance_id;
  struct id128_v1 entry_instance_id;
  struct id128_v1 authority_domain_id;
  struct id128_v1 binding_id;
  struct id128_v1 execution_set_id;
  struct exact_file_object_key_v1 file_object;
  uint64_t exact_object_key_id;
  uint64_t composite_atom_id;
  uint32_t active_role_id;
  uint32_t process_state_vector_id;
  uint16_t entry_kind;
  uint16_t effect_family;
  uint16_t operation;
  int16_t configured_errno;
  int32_t kernel_result;
  uint8_t reason;
  uint8_t physical_result;
  uint8_t reserved[2];
  struct id128_v1 controller_process_state_id;
  uint64_t controller_transition_version;
  uint64_t target_task_cookie;
  uint64_t target_profile_generation_ref_id;
  struct id128_v1 target_process_state_id;
  uint64_t target_transition_version;
  uint32_t target_role_id;
  uint32_t target_process_state_vector_id;
  uint32_t operation_argument;
  uint8_t reserved_process_control[4];
  uint64_t network_socket_key_id;
  uint64_t network_socket_generation;
  uint64_t network_flow_generation;
  struct id128_v1 network_flow_authorization_id;
  uint64_t network_destination_policy_handle;
  uint64_t network_creator_destination_policy_handle;
  uint64_t network_flow_authorizer_profile_generation_ref_id;
  uint64_t network_parent_socket_key_id;
  uint64_t network_parent_socket_generation;
  struct network_namespace_generation_v1 network_namespace;
  struct network_namespace_generation_v1 network_current_namespace;
  uint64_t network_creator_profile_generation_ref_id;
  uint8_t network_peer_address[16];
  uint16_t network_peer_port;
  uint8_t network_address_family;
  uint8_t network_protocol;
  uint8_t network_socket_state;
  uint8_t network_response_scope;
  uint8_t reserved_network[2];
  struct id128_v1 io_uring_ring_id;
  uint64_t io_uring_ring_generation;
  uint64_t io_uring_submission_sequence;
  uint64_t io_uring_user_data;
  int64_t io_uring_file_offset;
  uint64_t io_uring_buffer_address;
  uint64_t io_uring_file_cookie;
  uint64_t io_uring_executor_pid_tgid;
  uint32_t io_uring_byte_length;
  uint32_t io_uring_sqe_index;
  uint32_t io_uring_request_flags;
  uint32_t io_uring_rw_flags;
  uint16_t io_uring_opcode;
  uint8_t reserved_io_uring[6];
} effect_observation_v1;

typedef struct exact_object_binding_v1 {
  uint64_t profile_generation_ref_id;
  uint64_t exact_object_key_id;
  uint64_t composite_atom_id;
  exact_object_binding_state_v1 state;
  uint8_t reserved[7];
} exact_object_binding_v1;

typedef struct exception_handle_binding_key_v1 {
  uint64_t profile_generation_ref_id;
  uint32_t exception_numeric_handle;
  uint32_t reserved;
} exception_handle_binding_key_v1;

typedef struct exception_runtime_state_key_v1 {
  struct id128_v1 node_id;
  struct id128_v1 exception_instance_id;
} exception_runtime_state_key_v1;

typedef struct exception_handle_binding_v1 {
  struct exception_runtime_state_key_v1 runtime_state_key;
  exception_binding_state_v1 state;
  uint8_t reserved[7];
} exception_handle_binding_v1;

typedef struct exception_runtime_state_v1 {
  uint32_t lock;
  uint32_t maximum_uses;
  uint32_t consumed_uses;
  uint32_t bound_profile_generation_refs;
  uint64_t deadline_boottime_ns;
  uint64_t transition_version;
  uint8_t exception_definition_sha256[32];
  exception_runtime_state_kind_v1 state;
  uint8_t reserved[7];
} exception_runtime_state_v1;

typedef struct exception_use_identity_v1 {
  exception_use_identity_kind_v1 kind;
  uint8_t reserved_0[7];
  struct id128_v1 claim_slot_id;
  uint64_t task_cookie;
  struct id128_v1 process_state_id;
  uint64_t syscall_entry_sequence;
  uint64_t effect_attempt_sequence;
  uint16_t effect_family;
  uint16_t operation;
  uint8_t reserved_1[4];
} exception_use_identity_v1;

typedef struct exception_use_receipt_key_v1 {
  struct exception_runtime_state_key_v1 runtime_state_key;
  struct exception_use_identity_v1 use_identity;
} exception_use_receipt_key_v1;

typedef struct exception_use_receipt_v1 {
  uint32_t consumed_ordinal;
  exception_receipt_state_v1 state;
  uint8_t reserved[3];
  uint64_t claimed_boottime_ns;
  uint64_t transition_version;
} exception_use_receipt_v1;

typedef struct file_open_event_v1 {
  uint64_t inode;
  int32_t result;
  uint32_t reserved;
} file_open_event_v1;

typedef struct file_open_target_v1 {
  uint64_t inode;
} file_open_target_v1;

typedef struct identity_health_v1 {
  uint64_t allocation_failures;
  uint64_t coordinate_failures;
  uint64_t placement_mismatches;
  uint64_t missing_identity_denials;
  uint64_t exec_guard_denials;
  uint64_t reconciliation_required;
} identity_health_v1;

typedef struct identity_runtime_config_v1 {
  struct id128_v1 node_boot_id;
  uint64_t label_epoch;
  uint64_t next_id;
  uint64_t effect_controller_cgroup_id;
  int32_t first_effect_errno;
  uint8_t enabled;
  uint8_t effect_policy_enabled;
  uint8_t reserved[2];
} identity_runtime_config_v1;

typedef struct runtime_bootstrap_object_key_v1 {
  uint64_t inode;
  uint64_t filesystem_magic;
  uint32_t filesystem_device;
  uint32_t inode_generation;
} runtime_bootstrap_object_key_v1;

typedef struct runtime_bootstrap_object_state_v1 {
  struct id128_v1 binding_id;
  struct id128_v1 binding_nonce;
  struct id128_v1 entry_instance_id;
  uint64_t deadline_boottime_ns;
  uint64_t transition_version;
  runtime_bootstrap_object_kind_v1 kind;
  uint8_t reserved[7];
} runtime_bootstrap_object_state_v1;

typedef struct io_uring_actor_snapshot_v1 {
  struct id128_v1 node_boot_id;
  struct id128_v1 process_lineage_id;
  struct id128_v1 process_instance_id;
  struct id128_v1 process_state_id;
  struct id128_v1 entry_instance_id;
  struct id128_v1 authority_domain_id;
  struct id128_v1 binding_id;
  struct id128_v1 binding_nonce;
  struct id128_v1 execution_set_id;
  struct id128_v1 profile_id;
  uint64_t task_cookie;
  uint64_t label_epoch;
  uint64_t profile_generation_ref_id;
  uint64_t root_cgroup_id;
  uint64_t container_generation;
  uint64_t lifecycle_generation;
  uint64_t process_transition_version;
  uint32_t active_role_id;
  uint32_t process_state_vector_id;
  uint16_t entry_kind;
  binding_lifecycle_state_v1 binding_lifecycle_state;
  uint8_t reserved[5];
} io_uring_actor_snapshot_v1;

typedef struct io_uring_execution_state_v1 {
  struct id128_v1 ring_id;
  uint64_t context_cookie;
  uint64_t request_cookie;
  uint64_t submission_sequence;
  uint64_t user_data;
  uint64_t executor_pid_tgid;
  uint16_t opcode;
  io_uring_execution_state_kind_v1 state;
  uint8_t reserved[5];
} io_uring_execution_state_v1;

typedef struct io_uring_request_state_v1 {
  struct io_uring_actor_snapshot_v1 actor;
  struct id128_v1 ring_id;
  uint64_t context_cookie;
  uint64_t request_cookie;
  uint64_t ring_generation;
  uint64_t submission_sequence;
  uint64_t user_data;
  int64_t file_offset;
  uint64_t buffer_address;
  uint64_t file_cookie;
  uint64_t transition_version;
  uint32_t byte_length;
  uint32_t sqe_index;
  uint32_t request_flags;
  uint32_t rw_flags;
  uint16_t opcode;
  io_uring_request_state_kind_v1 state;
  uint8_t reserved[5];
} io_uring_request_state_v1;

typedef struct io_uring_ring_state_v1 {
  struct io_uring_actor_snapshot_v1 owner;
  struct execution_set_binding_state_v1 binding;
  struct id128_v1 ring_id;
  uint64_t context_cookie;
  uint64_t ring_generation;
  uint64_t next_submission_sequence;
  uint64_t transition_version;
  uint64_t outstanding_requests;
  uint32_t sq_entries;
  uint32_t cq_entries;
  uint32_t setup_flags;
  io_uring_ring_state_kind_v1 state;
  io_uring_restriction_state_v1 restriction_state;
  uint8_t reserved[2];
} io_uring_ring_state_v1;

typedef struct io_uring_setup_state_v1 {
  uint64_t task_cookie;
  uint64_t setup_attempt_sequence;
  uint32_t entries;
  uint32_t flags;
  io_uring_setup_state_kind_v1 state;
  uint8_t reserved[7];
} io_uring_setup_state_v1;

typedef struct ipc_relationship_decision_key_v1 {
  uint64_t actor_profile_generation_ref_id;
  uint32_t actor_role_id;
  uint32_t peer_role_id;
  ipc_channel_kind_v1 channel_kind;
  ipc_operation_v1 operation;
  uint8_t reserved[6];
} ipc_relationship_decision_key_v1;

typedef struct ipc_socket_state_v1 {
  struct id128_v1 channel_state_id;
  struct id128_v1 endpoint_a_process_state_id;
  struct id128_v1 endpoint_b_process_state_id;
  struct id128_v1 endpoint_a_binding_id;
  struct id128_v1 endpoint_b_binding_id;
  struct id128_v1 endpoint_a_binding_nonce;
  struct id128_v1 endpoint_b_binding_nonce;
  struct id128_v1 endpoint_a_execution_set_id;
  struct id128_v1 endpoint_b_execution_set_id;
  uint64_t endpoint_a_profile_generation_ref_id;
  uint64_t endpoint_b_profile_generation_ref_id;
  uint64_t endpoint_a_process_transition_version;
  uint64_t endpoint_b_process_transition_version;
  uint64_t endpoint_a_root_cgroup_id;
  uint64_t endpoint_b_root_cgroup_id;
  uint32_t endpoint_a_role_id;
  uint32_t endpoint_b_role_id;
  uint64_t transition_version;
  ipc_channel_kind_v1 channel_kind;
  ipc_socket_state_kind_v1 state;
  uint8_t reserved[6];
} ipc_socket_state_v1;

typedef struct kernel_real_parent_interval_key_v1 {
  uint64_t child_task_cookie;
  uint64_t interval_sequence;
} kernel_real_parent_interval_key_v1;

typedef struct kernel_real_parent_interval_v1 {
  uint64_t child_task_cookie;
  uint64_t real_parent_task_cookie;
  uint32_t real_parent_host_tid;
  uint32_t real_parent_host_tgid;
  uint32_t real_parent_pid_namespace_inode;
  kernel_real_parent_change_reason_v1 change_reason;
  uint8_t kernel_direct_proof;
  uint8_t reserved[2];
  uint64_t real_parent_start_boottime_ns;
  uint64_t interval_start_boottime_ns;
  uint64_t interval_end_boottime_ns;
  uint64_t transition_version;
} kernel_real_parent_interval_v1;

typedef struct network_port_range_v1 {
  uint16_t first;
  uint16_t last;
} network_port_range_v1;

typedef struct network_destination_class_v1 {
  uint64_t destination_policy_handle;
  struct network_port_range_v1 port_ranges[MAX_NETWORK_PORT_RANGES_V1];
  uint8_t port_range_count;
  uint8_t reserved[7];
} network_destination_class_v1;

typedef struct network_destination_decision_key_v1 {
  uint64_t profile_generation_ref_id;
  uint64_t destination_policy_handle;
  uint32_t active_role_id;
  uint32_t process_state_vector_id;
  uint16_t entry_kind;
  uint16_t operation;
  network_protocol_v1 protocol;
  binding_lifecycle_state_v1 binding_lifecycle_state;
  uint8_t reserved[2];
} network_destination_decision_key_v1;

typedef struct network_ipv4_lpm_key_v1 {
  uint32_t prefix_length;
  uint32_t reserved_alignment;
  uint64_t profile_generation_ref_id;
  network_protocol_v1 protocol;
  uint8_t reserved[7];
  uint8_t address[4];
  uint8_t reserved_tail[4];
} network_ipv4_lpm_key_v1;

typedef struct network_ipv6_lpm_key_v1 {
  uint32_t prefix_length;
  uint32_t reserved_alignment;
  uint64_t profile_generation_ref_id;
  network_protocol_v1 protocol;
  uint8_t reserved[7];
  uint8_t address[16];
} network_ipv6_lpm_key_v1;

typedef struct network_response_floor_key_v1 {
  uint64_t profile_generation_ref_id;
  uint64_t socket_key_id;
  uint64_t socket_generation;
} network_response_floor_key_v1;

typedef struct network_response_floor_v1 {
  network_response_scope_v1 scope;
  uint8_t reserved[7];
} network_response_floor_v1;

typedef struct network_socket_state_v1 {
  struct network_namespace_generation_v1 socket_network_namespace;
  uint64_t creator_profile_generation_ref_id;
  uint64_t socket_key_id;
  uint64_t socket_generation;
  uint64_t flow_generation;
  struct id128_v1 flow_authorization_id;
  uint64_t destination_policy_handle;
  uint64_t creator_destination_policy_handle;
  uint64_t flow_authorizer_profile_generation_ref_id;
  uint64_t parent_socket_key_id;
  uint64_t parent_socket_generation;
  uint32_t creator_role_id;
  uint32_t creator_process_state_vector_id;
  uint16_t creator_entry_kind;
  network_address_family_v1 address_family;
  network_protocol_v1 protocol;
  uint16_t peer_port;
  uint8_t peer_address[16];
  binding_lifecycle_state_v1 creator_binding_lifecycle_state;
  network_socket_state_kind_v1 state;
} network_socket_state_v1;

typedef struct mount_mutation_attempt_v1 {
  uint32_t mount_namespace_inode;
  uint8_t active;
  uint8_t reserved[3];
} mount_mutation_attempt_v1;

typedef struct mount_reconciliation_proposal_v1 {
  uint64_t topology_generation;
  uint64_t snapshot_digest_id;
  uint64_t expected_transition_version;
  uint64_t transition_version;
} mount_reconciliation_proposal_v1;

typedef struct mount_security_view_state_v1 {
  uint64_t topology_generation;
  uint64_t snapshot_digest_id;
  uint64_t pending_mutations;
  mount_topology_state_v1 state;
  uint8_t reserved[7];
  uint64_t transition_version;
} mount_security_view_state_v1;

typedef struct pending_exec_v1 {
  struct id128_v1 pending_exec_id;
  uint64_t task_cookie;
  struct id128_v1 process_state_id;
  uint64_t exec_attempt_sequence;
  struct id128_v1 source_execution_id;
  uint32_t source_role_id;
  uint16_t candidate_count;
  uint8_t runtime_bootstrap_exec;
  uint8_t reserved_0;
  uint64_t source_profile_generation_ref_id;
  uint64_t pending_exec_response_set_ref_id;
  struct id128_v1 target_execution_id;
  struct id128_v1 target_image_provenance_id;
  struct exact_executable_candidate_v1 ordered_candidates[MAX_EXEC_CANDIDATES_V1];
  uint64_t transition_version;
  pending_exec_state_v1 state;
  uint8_t reserved_1[7];
} pending_exec_v1;

typedef struct pending_administrative_match_v1 {
  uint64_t task_cookie;
  uint64_t exec_attempt_sequence;
  struct id128_v1 proof_id;
  struct id128_v1 claim_slot_id;
  uint32_t approved_role_numeric_id;
  uint32_t reserved_0;
  uint64_t profile_generation_ref_id;
  struct exact_executable_candidate_v1 resolved_executable;
  uint64_t transition_version;
  pending_administrative_match_state_v1 state;
  uint8_t reserved_1[7];
} pending_administrative_match_v1;

typedef struct physical_decision_v1 {
  physical_decision_kind_v1 decision;
  uint8_t reserved;
  int16_t errno;
  uint32_t evidence_class_id;
  uint32_t transition_id;
  uint32_t exception_numeric_handle;
} physical_decision_v1;

typedef struct policy_activation_probe_v1 {
  policy_activation_probe_map_kind_v1 map_kind;
  uint8_t reserved[7];
  uint32_t key_size;
  uint32_t reserved_alignment;
  uint8_t key[MAX_POLICY_ACTIVATION_PROBE_KEY_BYTES_V1];
  struct physical_decision_v1 expected;
} policy_activation_probe_v1;

typedef struct path_graph_state_key_v1 {
  uint64_t profile_generation_ref_id;
  uint32_t state_id;
  uint32_t reserved;
} path_graph_state_key_v1;

typedef struct path_graph_terminal_v1 {
  uint64_t composite_atom_id;
  uint32_t rule_numeric_id;
  uint8_t exact_object_required;
  uint8_t reserved[3];
  uint64_t path_tree_deny_operation_mask;
} path_graph_terminal_v1;

typedef struct path_graph_transition_key_v1 {
  uint64_t profile_generation_ref_id;
  uint32_t current_state_id;
  struct canonical_path_component_v1 component;
  uint16_t reserved;
} path_graph_transition_key_v1;

typedef struct path_graph_transition_v1 {
  uint32_t next_state_id;
  uint32_t reserved;
} path_graph_transition_v1;

typedef struct profile_generation_descriptor_v1 {
  struct id128_v1 node_boot_id;
  struct id128_v1 profile_id;
  uint64_t label_epoch;
  uint64_t profile_generation_ref_id;
  uint64_t owner_generation;
  uint32_t row_count;
  uint32_t default_count;
  policy_generation_state_v1 state;
  policy_generation_mode_v1 mode;
  uint8_t reserved[6];
  uint8_t table_digest[32];
  uint64_t transition_version;
} profile_generation_descriptor_v1;

typedef struct process_security_state_v1 {
  struct id128_v1 process_state_id;
  struct id128_v1 node_boot_id;
  uint64_t label_epoch;
  struct id128_v1 process_lineage_id;
  struct id128_v1 process_instance_id;
  struct id128_v1 entry_instance_id;
  struct id128_v1 entry_root_process_state_id;
  struct id128_v1 active_execution_id;
  uint32_t active_role_id;
  uint32_t process_state_vector_id;
  uint64_t active_profile_generation_ref_id;
  struct id128_v1 authority_domain_id;
  uint64_t effective_response_set_ref_id;
  struct id128_v1 pending_exec_id;
  struct id128_v1 pending_target_execution_id;
  uint32_t pending_target_role_id;
  uint32_t reserved_pending_role;
  uint64_t transition_guard;
  uint64_t pending_exec_response_set_ref_id;
  uint64_t exec_check_task_cookie;
  uint64_t transition_version;
  uint64_t live_thread_refs;
  exec_guard_state_v1 exec_guard_state;
  process_security_state_kind_v1 state;
  uint8_t reserved[6];
} process_security_state_v1;

typedef struct process_control_rule_key_v1 {
  uint64_t profile_generation_ref_id;
  uint32_t controller_role_id;
  uint32_t controller_process_state_vector_id;
  uint32_t target_role_id;
  uint32_t target_process_state_vector_id;
  uint32_t operation_argument;
  uint16_t entry_kind;
  uint16_t operation;
  binding_lifecycle_state_v1 binding_lifecycle_state;
  uint8_t argument_wildcard;
  uint8_t reserved[6];
} process_control_rule_key_v1;

typedef struct process_state_vector_v1 {
  struct id128_v1 node_boot_id;
  uint64_t label_epoch;
  uint64_t state_bits;
  uint64_t profile_generation_ref_id;
  uint64_t transition_version;
  uint32_t process_state_vector_id;
  process_state_vector_state_v1 state;
  uint8_t reserved[3];
} process_state_vector_v1;

typedef struct process_execution_instance_v1 {
  struct id128_v1 process_execution_instance_id;
  struct id128_v1 process_lineage_id;
  struct id128_v1 image_provenance_id;
  uint64_t start_boottime_ns;
  uint64_t end_boottime_ns;
  uint64_t transition_version;
  process_execution_started_by_v1 started_by;
  process_execution_state_v1 state;
  uint8_t reserved[6];
} process_execution_instance_v1;

typedef struct task_coordinate_v1 {
  uint64_t task_cookie;
  struct id128_v1 process_instance_id;
  struct id128_v1 process_state_id;
  uint64_t task_start_boottime_ns;
  uint64_t finalized_boottime_ns;
  uint64_t real_parent_interval_sequence;
  uint64_t transition_version;
  uint32_t host_tid;
  uint32_t host_tgid;
  uint32_t pid_namespace_inode;
  task_coordinate_state_v1 state;
  uint8_t reserved[3];
} task_coordinate_v1;

typedef struct task_effect_attempt_frame_v1 {
  uint64_t effect_attempt_sequence;
  uint16_t effect_family;
  uint16_t operation;
  effect_attempt_hook_v1 hook_discriminator;
  uint16_t repeated_lsm_pass_count;
  task_effect_attempt_frame_state_v1 state;
  uint8_t reserved[7];
} task_effect_attempt_frame_v1;

typedef struct task_effect_attempt_state_v1 {
  uint64_t task_cookie;
  uint64_t syscall_entry_sequence;
  uint64_t next_effect_attempt_sequence;
  struct task_effect_attempt_frame_v1 frames[MAX_NESTED_EFFECT_ATTEMPTS_V1];
  uint16_t depth;
  task_effect_attempt_state_kind_v1 state;
  uint8_t reserved[5];
} task_effect_attempt_state_v1;

typedef struct task_placement_expectation_v1 {
  struct id128_v1 protected_root_binding_id;
  struct id128_v1 protected_root_binding_nonce;
  uint32_t allowed_descendant_policy_id;
  uint32_t reserved;
} task_placement_expectation_v1;

typedef struct task_label_v1 {
  struct id128_v1 node_boot_id;
  uint64_t label_epoch;
  uint64_t task_cookie;
  struct id128_v1 process_lineage_id;
  struct id128_v1 process_instance_id;
  struct id128_v1 process_state_id;
  struct id128_v1 entry_instance_id;
  struct id128_v1 execution_set_id;
  uint64_t birth_profile_generation_ref_id;
  struct id128_v1 birth_execution_id;
  struct id128_v1 birth_authority_domain_id;
  uint16_t lineage_depth;
  uint8_t reserved[6];
  struct id128_v1 ancestor_process_lineage_ids[MAX_ANCESTOR_PROCESS_LINEAGES_V1];
  struct task_placement_expectation_v1 placement;
} task_label_v1;

typedef struct task_label_candidate_v1 {
  uint64_t label;
} task_label_candidate_v1;

typedef struct task_reference_tombstone_v1 {
  uint64_t task_cookie;
  struct id128_v1 birth_transaction_id;
  uint64_t birth_transition_version;
  struct id128_v1 entry_instance_id;
  struct id128_v1 process_state_id;
  struct id128_v1 authority_domain_id_at_birth;
  uint64_t profile_generation_ref_id;
  uint64_t acquired_bits;
  uint64_t released_bits;
  uint64_t transition_version;
  uint8_t task_free_observed;
  uint8_t wal_acknowledged;
  reference_tombstone_state_v1 state;
  uint8_t reserved[5];
} task_reference_tombstone_v1;

#endif /* EREBOR_INTERCEPTOR_ABI_H */
