#ifndef EREBOR_INTERCEPTOR_ABI_H
#define EREBOR_INTERCEPTOR_ABI_H

#ifdef __BPF__
typedef __u8 uint8_t;
typedef __u16 uint16_t;
typedef __u32 uint32_t;
typedef __u64 uint64_t;
typedef __s16 int16_t;
typedef __s32 int32_t;
#else
#include <stdint.h>
#endif


/* Generated by cbindgen from erebor-interceptor-abi. Do not edit. */

#define MAX_ANCESTOR_PROCESS_LINEAGES_V1 8

#define MAX_EXEC_CANDIDATES_V1 8

#define TASK_REFERENCE_ENTRY_V1 (1 << 0)

#define TASK_REFERENCE_PROCESS_V1 (1 << 1)

#define TASK_REFERENCE_PROFILE_GENERATION_V1 (1 << 2)

#define TASK_REFERENCE_ALL_V1 ((TASK_REFERENCE_ENTRY_V1 | TASK_REFERENCE_PROCESS_V1) | TASK_REFERENCE_PROFILE_GENERATION_V1)

#define TASK_ALLOC_HOOK_LSM_V1 1

#define CONSERVATIVE_PROCESS_STATE_VECTOR_V1 1

enum binding_lifecycle_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  binding_lifecycle_state_v1_unknown = 0,
  binding_lifecycle_state_v1_preparing = 1,
  binding_lifecycle_state_v1_active = 2,
  binding_lifecycle_state_v1_draining = 3,
  binding_lifecycle_state_v1_terminating = 4,
  binding_lifecycle_state_v1_tombstoned = 5,
};
#if __STDC_VERSION__ >= 202311L
typedef enum binding_lifecycle_state_v1 binding_lifecycle_state_v1;
#else
typedef uint8_t binding_lifecycle_state_v1;
#endif // __STDC_VERSION__ >= 202311L

enum authority_domain_state_kind_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  authority_domain_state_kind_v1_unknown = 0,
  authority_domain_state_kind_v1_preparing = 1,
  authority_domain_state_kind_v1_active = 2,
  authority_domain_state_kind_v1_reclaimable = 3,
  authority_domain_state_kind_v1_fail_closed_overflow = 4,
  authority_domain_state_kind_v1_corrupt = 5,
};
#if __STDC_VERSION__ >= 202311L
typedef enum authority_domain_state_kind_v1 authority_domain_state_kind_v1;
#else
typedef uint8_t authority_domain_state_kind_v1;
#endif // __STDC_VERSION__ >= 202311L

enum entry_admission_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  entry_admission_state_v1_unknown = 0,
  entry_admission_state_v1_pending = 1,
  entry_admission_state_v1_claiming = 2,
  entry_admission_state_v1_committed = 3,
  entry_admission_state_v1_terminal = 4,
};
#if __STDC_VERSION__ >= 202311L
typedef enum entry_admission_state_v1 entry_admission_state_v1;
#else
typedef uint8_t entry_admission_state_v1;
#endif // __STDC_VERSION__ >= 202311L

enum entry_kind_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  entry_kind_v1_unknown = 0,
  entry_kind_v1_container_start = 1,
  entry_kind_v1_qualified_exec_probe = 2,
  entry_kind_v1_qualified_lifecycle_poststart = 3,
  entry_kind_v1_qualified_lifecycle_prestop = 4,
  entry_kind_v1_approved_administrative_exec_next_match = 5,
  entry_kind_v1_ephemeral_container = 6,
  entry_kind_v1_qualified_ci_container_action = 7,
  entry_kind_v1_checkpoint_restore_unknown = 8,
  entry_kind_v1_unknown_external = 9,
};
#if __STDC_VERSION__ >= 202311L
typedef enum entry_kind_v1 entry_kind_v1;
#else
typedef uint8_t entry_kind_v1;
#endif // __STDC_VERSION__ >= 202311L

enum entry_lifetime_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  entry_lifetime_state_v1_inactive = 0,
  entry_lifetime_state_v1_active = 1,
  entry_lifetime_state_v1_draining = 2,
  entry_lifetime_state_v1_complete = 3,
};
#if __STDC_VERSION__ >= 202311L
typedef enum entry_lifetime_state_v1 entry_lifetime_state_v1;
#else
typedef uint8_t entry_lifetime_state_v1;
#endif // __STDC_VERSION__ >= 202311L

enum entry_purpose_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  entry_purpose_v1_unknown = 0,
  entry_purpose_v1_qualified_joined_purpose = 1,
  entry_purpose_v1_approved_administrative_next_match = 2,
};
#if __STDC_VERSION__ >= 202311L
typedef enum entry_purpose_v1 entry_purpose_v1;
#else
typedef uint8_t entry_purpose_v1;
#endif // __STDC_VERSION__ >= 202311L

enum exec_guard_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  exec_guard_state_v1_none = 0,
  exec_guard_state_v1_preparing = 1,
  exec_guard_state_v1_commit_pending = 2,
  exec_guard_state_v1_outcome_unknown = 3,
};
#if __STDC_VERSION__ >= 202311L
typedef enum exec_guard_state_v1 exec_guard_state_v1;
#else
typedef uint8_t exec_guard_state_v1;
#endif // __STDC_VERSION__ >= 202311L

enum initial_root_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint64_t
#endif // __STDC_VERSION__ >= 202311L
 {
  initial_root_state_v1_unarmed = 0,
  initial_root_state_v1_available = 1,
  initial_root_state_v1_consumed = 2,
};
#if __STDC_VERSION__ >= 202311L
typedef enum initial_root_state_v1 initial_root_state_v1;
#else
typedef uint64_t initial_root_state_v1;
#endif // __STDC_VERSION__ >= 202311L

enum external_root_class_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  external_root_class_v1_unknown = 0,
  external_root_class_v1_initial_container_root = 1,
  external_root_class_v1_external_runtime_root = 2,
  external_root_class_v1_restored_or_unknown_root = 3,
  external_root_class_v1_unresolved_protected = 4,
};
#if __STDC_VERSION__ >= 202311L
typedef enum external_root_class_v1 external_root_class_v1;
#else
typedef uint8_t external_root_class_v1;
#endif // __STDC_VERSION__ >= 202311L

enum installed_role_class_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  installed_role_class_v1_unknown = 0,
  installed_role_class_v1_initial_role = 1,
  installed_role_class_v1_runtime_external_restricted = 2,
  installed_role_class_v1_fail_closed_unknown = 3,
  installed_role_class_v1_qualified_registered_role = 4,
  installed_role_class_v1_approved_administrative_role = 5,
};
#if __STDC_VERSION__ >= 202311L
typedef enum installed_role_class_v1 installed_role_class_v1;
#else
typedef uint8_t installed_role_class_v1;
#endif // __STDC_VERSION__ >= 202311L

enum pending_exec_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  pending_exec_state_v1_unknown = 0,
  pending_exec_state_v1_preparing = 1,
  pending_exec_state_v1_commit_pending = 2,
  pending_exec_state_v1_pre_ponr_failed = 3,
  pending_exec_state_v1_post_ponr_fatal = 4,
  pending_exec_state_v1_success = 5,
  pending_exec_state_v1_outcome_unknown = 6,
};
#if __STDC_VERSION__ >= 202311L
typedef enum pending_exec_state_v1 pending_exec_state_v1;
#else
typedef uint8_t pending_exec_state_v1;
#endif // __STDC_VERSION__ >= 202311L

enum physical_decision_kind_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  physical_decision_kind_v1_allow = 0,
  physical_decision_kind_v1_audit_allow = 1,
  physical_decision_kind_v1_deny = 2,
};
#if __STDC_VERSION__ >= 202311L
typedef enum physical_decision_kind_v1 physical_decision_kind_v1;
#else
typedef uint8_t physical_decision_kind_v1;
#endif // __STDC_VERSION__ >= 202311L

enum process_security_state_kind_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  process_security_state_kind_v1_unknown = 0,
  process_security_state_kind_v1_allocating = 1,
  process_security_state_kind_v1_active = 2,
  process_security_state_kind_v1_exiting = 3,
  process_security_state_kind_v1_reclaimable = 4,
  process_security_state_kind_v1_fail_closed_overflow = 5,
  process_security_state_kind_v1_corrupt = 6,
};
#if __STDC_VERSION__ >= 202311L
typedef enum process_security_state_kind_v1 process_security_state_kind_v1;
#else
typedef uint8_t process_security_state_kind_v1;
#endif // __STDC_VERSION__ >= 202311L

enum reference_tombstone_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  reference_tombstone_state_v1_unknown = 0,
  reference_tombstone_state_v1_preparing = 1,
  reference_tombstone_state_v1_owned = 2,
  reference_tombstone_state_v1_released = 3,
  reference_tombstone_state_v1_reclaimable = 4,
};
#if __STDC_VERSION__ >= 202311L
typedef enum reference_tombstone_state_v1 reference_tombstone_state_v1;
#else
typedef uint8_t reference_tombstone_state_v1;
#endif // __STDC_VERSION__ >= 202311L

enum task_coordinate_state_v1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  task_coordinate_state_v1_unknown = 0,
  task_coordinate_state_v1_allocating = 1,
  task_coordinate_state_v1_coordinates_finalized = 2,
  task_coordinate_state_v1_runnable = 3,
  task_coordinate_state_v1_exited = 4,
  task_coordinate_state_v1_failed = 5,
  task_coordinate_state_v1_fail_closed_unknown = 6,
};
#if __STDC_VERSION__ >= 202311L
typedef enum task_coordinate_state_v1 task_coordinate_state_v1;
#else
typedef uint8_t task_coordinate_state_v1;
#endif // __STDC_VERSION__ >= 202311L

typedef struct id128_v1 {
  uint64_t high;
  uint64_t low;
} id128_v1;
#define id128_v1_ZERO (id128_v1){ .high = 0, .low = 0 }

typedef struct created_by_edge_v1 {
  uint64_t child_task_cookie;
  uint64_t creator_task_cookie;
  struct id128_v1 child_process_lineage_id;
  struct id128_v1 creator_process_lineage_id;
  struct id128_v1 clone_attempt_id;
  uint64_t clone_flags;
  uint32_t task_alloc_hook_id;
  uint32_t reserved;
} created_by_edge_v1;

typedef struct authority_domain_state_v1 {
  struct id128_v1 authority_domain_id;
  struct id128_v1 node_boot_id;
  uint64_t label_epoch;
  uint64_t domain_epoch;
  uint64_t live_process_refs;
  uint64_t response_plan_refs;
  uint64_t reconciliation_hold_refs;
  uint64_t potential_sensitive_bits;
  uint64_t observed_sensitive_bits;
  uint64_t effective_restriction_set_ref_id;
  uint64_t effective_response_set_ref_id;
  uint64_t retained_generation_set_ref_id;
  uint64_t transition_version;
  uint64_t transition_guard;
  authority_domain_state_kind_v1 state;
  uint8_t reserved[7];
} authority_domain_state_v1;

typedef struct entry_security_state_v1 {
  struct id128_v1 entry_instance_id;
  struct id128_v1 node_boot_id;
  uint64_t label_epoch;
  struct id128_v1 execution_set_id;
  struct id128_v1 claim_slot_id;
  uint64_t root_task_cookie;
  struct id128_v1 root_process_state_id;
  struct id128_v1 committed_execution_id;
  uint64_t live_task_refs;
  uint64_t transition_version;
  entry_kind_v1 entry_kind;
  entry_admission_state_v1 admission_state;
  entry_lifetime_state_v1 lifetime_state;
  uint8_t terminal_reason;
  uint8_t reserved_state[4];
  uint64_t transition_guard;
} entry_security_state_v1;

typedef struct exact_executable_candidate_v1 {
  uint64_t mount_id;
  uint64_t inode;
  uint64_t inode_generation;
} exact_executable_candidate_v1;

typedef struct execution_set_binding_state_v1 {
  struct id128_v1 binding_id;
  struct id128_v1 binding_nonce;
  struct id128_v1 node_boot_id;
  struct id128_v1 execution_set_id;
  struct id128_v1 profile_id;
  uint64_t label_epoch;
  uint64_t active_profile_generation_ref_id;
  uint64_t root_cgroup_id;
  struct id128_v1 root_cgroup_live_interval_id;
  uint64_t lifecycle_generation;
  uint64_t transition_version;
  uint32_t initial_role_id;
  uint32_t external_role_id;
  binding_lifecycle_state_v1 lifecycle_state;
  uint8_t reserved[7];
  initial_root_state_v1 initial_root_state;
} execution_set_binding_state_v1;

typedef struct external_root_classification_v1 {
  struct id128_v1 node_boot_id;
  uint64_t label_epoch;
  uint64_t task_cookie;
  struct id128_v1 process_state_id;
  struct id128_v1 entry_instance_id;
  struct id128_v1 execution_set_id;
  struct id128_v1 cgroup_binding_id;
  struct id128_v1 cgroup_lifetime_id;
  uint64_t creator_task_cookie;
  uint64_t profile_generation_ref_id;
  uint32_t installed_role_numeric_id;
  external_root_class_v1 root_class;
  entry_purpose_v1 purpose;
  installed_role_class_v1 installed_role_class;
  uint8_t reserved;
  uint64_t classified_boottime_ns;
} external_root_classification_v1;

typedef struct effect_decision_key_v1 {
  uint64_t profile_generation_ref_id;
  uint32_t active_role_id;
  uint16_t entry_kind;
  uint16_t effect_family;
  uint16_t operation;
  uint16_t reserved;
  uint8_t reserved_alignment[4];
  uint64_t composite_atom_id;
  uint64_t exact_object_key_id;
  uint32_t process_state_vector_id;
  binding_lifecycle_state_v1 binding_lifecycle_state;
  uint8_t reserved_tail[3];
} effect_decision_key_v1;

typedef struct file_open_event_v1 {
  uint64_t inode;
  int32_t result;
  uint32_t reserved;
} file_open_event_v1;

typedef struct file_open_target_v1 {
  uint64_t inode;
} file_open_target_v1;

typedef struct identity_health_v1 {
  uint64_t allocation_failures;
  uint64_t coordinate_failures;
  uint64_t placement_mismatches;
  uint64_t missing_identity_denials;
  uint64_t exec_guard_denials;
  uint64_t reconciliation_required;
} identity_health_v1;

typedef struct identity_runtime_config_v1 {
  struct id128_v1 node_boot_id;
  uint64_t label_epoch;
  uint64_t next_id;
  int32_t first_effect_errno;
  uint8_t enabled;
  uint8_t reserved[3];
} identity_runtime_config_v1;

typedef struct pending_exec_v1 {
  struct id128_v1 pending_exec_id;
  uint64_t task_cookie;
  struct id128_v1 process_state_id;
  uint64_t exec_attempt_sequence;
  struct id128_v1 source_execution_id;
  uint32_t source_role_id;
  uint16_t candidate_count;
  uint16_t reserved_0;
  uint64_t source_profile_generation_ref_id;
  uint64_t pending_exec_response_set_ref_id;
  struct id128_v1 target_execution_id;
  struct exact_executable_candidate_v1 ordered_candidates[MAX_EXEC_CANDIDATES_V1];
  uint64_t transition_version;
  pending_exec_state_v1 state;
  uint8_t reserved_1[7];
} pending_exec_v1;

typedef struct physical_decision_v1 {
  physical_decision_kind_v1 decision;
  uint8_t reserved;
  int16_t errno;
  uint32_t evidence_class_id;
  uint32_t transition_id;
  uint32_t exception_numeric_handle;
} physical_decision_v1;

typedef struct process_security_state_v1 {
  struct id128_v1 process_state_id;
  struct id128_v1 node_boot_id;
  uint64_t label_epoch;
  struct id128_v1 process_lineage_id;
  struct id128_v1 process_instance_id;
  struct id128_v1 entry_instance_id;
  struct id128_v1 entry_root_process_state_id;
  struct id128_v1 active_execution_id;
  uint32_t active_role_id;
  uint32_t process_state_vector_id;
  uint64_t active_profile_generation_ref_id;
  struct id128_v1 authority_domain_id;
  uint64_t effective_response_set_ref_id;
  struct id128_v1 pending_exec_id;
  struct id128_v1 pending_target_execution_id;
  uint32_t pending_target_role_id;
  uint32_t reserved_pending_role;
  uint64_t transition_guard;
  uint64_t pending_exec_response_set_ref_id;
  uint64_t transition_version;
  uint64_t live_thread_refs;
  exec_guard_state_v1 exec_guard_state;
  process_security_state_kind_v1 state;
  uint8_t reserved[6];
} process_security_state_v1;

typedef struct task_coordinate_v1 {
  uint64_t task_cookie;
  struct id128_v1 process_instance_id;
  struct id128_v1 process_state_id;
  uint32_t host_tid;
  uint32_t host_tgid;
  uint64_t pid_namespace_inode;
  uint64_t task_start_boottime_ns;
  uint64_t finalized_boottime_ns;
  uint64_t transition_version;
  task_coordinate_state_v1 state;
  uint8_t reserved[7];
} task_coordinate_v1;

typedef struct task_placement_expectation_v1 {
  struct id128_v1 protected_root_binding_id;
  struct id128_v1 protected_root_binding_nonce;
  uint32_t allowed_descendant_policy_id;
  uint32_t reserved;
} task_placement_expectation_v1;

typedef struct task_label_v1 {
  struct id128_v1 node_boot_id;
  uint64_t label_epoch;
  uint64_t task_cookie;
  struct id128_v1 process_lineage_id;
  struct id128_v1 process_instance_id;
  struct id128_v1 process_state_id;
  struct id128_v1 entry_instance_id;
  struct id128_v1 execution_set_id;
  uint64_t birth_profile_generation_ref_id;
  struct id128_v1 birth_execution_id;
  struct id128_v1 birth_authority_domain_id;
  uint16_t lineage_depth;
  uint8_t reserved[6];
  struct id128_v1 ancestor_process_lineage_ids[MAX_ANCESTOR_PROCESS_LINEAGES_V1];
  struct task_placement_expectation_v1 placement;
} task_label_v1;

typedef struct task_label_candidate_v1 {
  uint64_t label;
} task_label_candidate_v1;

typedef struct task_reference_tombstone_v1 {
  uint64_t task_cookie;
  struct id128_v1 birth_transaction_id;
  uint64_t birth_transition_version;
  struct id128_v1 entry_instance_id;
  struct id128_v1 process_state_id;
  struct id128_v1 authority_domain_id_at_birth;
  uint64_t profile_generation_ref_id;
  uint64_t acquired_bits;
  uint64_t released_bits;
  uint64_t transition_version;
  uint8_t task_free_observed;
  uint8_t wal_acknowledged;
  reference_tombstone_state_v1 state;
  uint8_t reserved[5];
} task_reference_tombstone_v1;

#endif /* EREBOR_INTERCEPTOR_ABI_H */
