#ifndef EREBOR_INTERCEPTOR_ABI_H
#define EREBOR_INTERCEPTOR_ABI_H

#ifdef __BPF__
typedef __u8 uint8_t;
typedef __u16 uint16_t;
typedef __u32 uint32_t;
typedef __u64 uint64_t;
typedef __s16 int16_t;
typedef __s32 int32_t;
#else
#include <stdint.h>
#endif


/* Generated by cbindgen from erebor-interceptor-abi. Do not edit. */

enum BindingLifecycleStateV1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  BindingLifecycleStateV1_Unknown = 0,
  BindingLifecycleStateV1_Preparing = 1,
  BindingLifecycleStateV1_Active = 2,
  BindingLifecycleStateV1_Draining = 3,
  BindingLifecycleStateV1_Terminating = 4,
  BindingLifecycleStateV1_Tombstoned = 5,
};
#if __STDC_VERSION__ >= 202311L
typedef enum BindingLifecycleStateV1 BindingLifecycleStateV1;
#else
typedef uint8_t BindingLifecycleStateV1;
#endif // __STDC_VERSION__ >= 202311L

enum PhysicalDecisionKindV1
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  PhysicalDecisionKindV1_Allow = 0,
  PhysicalDecisionKindV1_AuditAllow = 1,
  PhysicalDecisionKindV1_Deny = 2,
};
#if __STDC_VERSION__ >= 202311L
typedef enum PhysicalDecisionKindV1 PhysicalDecisionKindV1;
#else
typedef uint8_t PhysicalDecisionKindV1;
#endif // __STDC_VERSION__ >= 202311L

typedef struct EffectDecisionKeyV1 {
  uint64_t profile_generation_ref_id;
  uint32_t active_role_id;
  uint16_t entry_kind;
  uint16_t effect_family;
  uint16_t operation;
  uint16_t reserved;
  uint8_t reserved_alignment[4];
  uint64_t composite_atom_id;
  uint64_t exact_object_key_id;
  uint32_t process_state_vector_id;
  BindingLifecycleStateV1 binding_lifecycle_state;
  uint8_t reserved_tail[3];
} EffectDecisionKeyV1;

typedef struct FileOpenEventV1 {
  uint64_t inode;
  int32_t result;
  uint32_t reserved;
} FileOpenEventV1;

typedef struct FileOpenTargetV1 {
  uint64_t inode;
} FileOpenTargetV1;

typedef struct PhysicalDecisionV1 {
  PhysicalDecisionKindV1 decision;
  uint8_t reserved;
  int16_t errno;
  uint32_t evidence_class_id;
  uint32_t transition_id;
  uint32_t exception_numeric_handle;
} PhysicalDecisionV1;

typedef struct TaskLabelCandidateV1 {
  uint64_t label;
} TaskLabelCandidateV1;

#endif /* EREBOR_INTERCEPTOR_ABI_H */
