[package]
name = "mithril-node"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clap.workspace = true
ed25519-dalek.workspace = true
erebor-interceptor = { path = "../erebor-interceptor" }
erebor-interceptor-abi = { path = "../erebor-interceptor-abi" }
erebor-runtime-client = { path = "../erebor-runtime-client" }
erebor-runtime-error = { path = "../erebor-runtime-error" }
erebor-runtime-ipc = { path = "../erebor-runtime-ipc" }
hyper-util.workspace = true
hex.workspace = true
k8s-cri.workspace = true
mithril-control = { path = "../mithril-control" }
minicbor.workspace = true
rustix = { version = "1.1.4", features = ["fs", "process", "time"] }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
snafu.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tonic.workspace = true
tower.workspace = true
uuid.workspace = true
zerocopy.workspace = true

[dev-dependencies]
rcgen = "0.13.2"
tempfile = "3.23.0"

[[bin]]
name = "mithril-node"
path = "src/main.rs"

[[bin]]
name = "mithril-inspect"
path = "src/bin/mithril_inspect.rs"

[lints]
workspace = true
