node:
  image: ereborlabs/mithril-node:dev
  imagePullPolicy: IfNotPresent
  logFilter: info
  configHostPath: /etc/mithril/node.json
  identityHostPath: /etc/mithril/identity
  stateHostPath: /var/lib/mithril
  runHostPath: /run/mithril
  containerRuntimeSocket: /run/containerd/containerd.sock
  nodeSelector: {}
  affinity: {}
  runtimeHook:
    hostBinaryDirectory: /usr/libexec/oci/hooks.d
    containerdConfigHostDirectory: /etc/containerd
    containerdDropInDirectory: conf.d
    runtimeCliHostPath: /usr/bin/ctr
    runtimeCliArgs:
      - oci
      - spec
    runtimeServices:
      - containerd
    socketPath: /run/mithril/runtime-admission.sock
    timeoutMs: 4000
    runtimeTimeoutSeconds: 5

control:
  enabled: true
  image: ereborlabs/mithril-control:dev
  imagePullPolicy: IfNotPresent
  logFilter: info
  configSecretName: mithril-control-config
  statePersistentVolumeClaim: mithril-control-state
  grpcPort: 8443
  nodeSelector: {}
  admission:
    enabled: true
    port: 9443
    tlsSecretName: mithril-admission-tls
    caBundle: ""
    webhookTimeoutSeconds: 5
