node:
  image: ereborlabs/mithril-node:dev
  configSecretName: mithril-node-config
  stateHostPath: /var/lib/mithril
  runHostPath: /run/mithril
  containerRuntimeSocket: /run/containerd/containerd.sock

control:
  enabled: true
  image: ereborlabs/mithril-control:dev
  configSecretName: mithril-control-config
  statePersistentVolumeClaim: mithril-control-state
  port: 8443
