[package]
name = "mithril-e2e"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
clap.workspace = true
ed25519-dalek.workspace = true
erebor-interceptor-abi = { path = "../erebor-interceptor-abi" }
erebor-interceptor = { path = "../erebor-interceptor" }
erebor-runtime-error = { path = "../erebor-runtime-error" }
erebor-runtime-ipc = { path = "../erebor-runtime-ipc" }
hex.workspace = true
libbpf-rs.workspace = true
libc = "0.2.186"
linux-raw-sys = { version = "0.12.1", features = ["general"] }
memmap2 = "0.9.11"
mithril-control = { path = "../mithril-control" }
mithril-node = { path = "../mithril-node" }
rustix = { version = "1.1.4", features = ["mount", "process", "thread"] }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
snafu.workspace = true
uuid.workspace = true
zerocopy.workspace = true

[dev-dependencies]
tempfile = "3.23.0"

[[bin]]
name = "mithril-kernel-qualification"
path = "src/bin/mithril_kernel_qualification.rs"

[[bin]]
name = "mithril-host-lifecycle-test"
path = "src/bin/mithril_host_lifecycle_test.rs"

[[bin]]
name = "mithril-identity-test"
path = "src/bin/mithril_identity_test.rs"

[[bin]]
name = "mithril-effect-test"
path = "src/bin/mithril_effect_test.rs"

[lints]
workspace = true
